In [15]:
import numpy as np
from numpy import array, dot, zeros
from numpy.linalg import inv
import scipy.linalg
np.set_printoptions(precision=4)

Истинное решение системы $A\mathbf{x}=\mathbf{b}$ по формуле $\mathbf{x}=A^{-1}\mathbf{b}$.

In [17]:
A = array([
    [3.3, -2.2,  -10,  1.7],
    [1.8, 21.1,  1.3, -2.2],
    [-10,  1.1,   20, -4.5],
    [ 70, -1.7, -2.2,  3.3]
])

b = array([1.1, 2.2, 10, 2.1])
dot(inv(A), b)

array([ 0.426 , -0.8658, -1.4467, -9.8102])

In [18]:
def solve_triangular(A, b):
    A = A.astype(np.float64); b = b.astype(np.float64)
    x = np.empty_like(b)
    for i in reversed(range(len(x))):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
    return x

### 1. Метод исключения Гаусса 

In [21]:
def gaussian_elimination(A, b=None):
    
    n = A.shape[0]
    if A.shape[1] != n or len(A.shape) != 2:
        raise ValueError("Matrix is not square!")
        
    if b is not None:
        if b.shape[0] != n:
            raise ValueError("Right-hand-side vector's shape does not match!")
        A = np.c_[A, b]
    
    for i in range(n):
        if np.allclose(A[i, i], .0):
            raise RuntimeError("Inappropriate matrix! Leading zero in row {}.".format(i))    
        A[i] = A[i] / A[i, i]
        A[i+1:, i:] = A[i+1:, i:] - np.outer(A[i+1:, i], A[i, i:])
        
    if b is None:
        return A
    return A[:, :-1], A[:, -1]

In [24]:
def gaussian_elimination_solve(A, b):
    
    A, b = gaussian_elimination(A, b)
    x = solve_triangular(A, b)
    return x

In [25]:
gaussian_elimination_solve(A, b)

array([ 0.426 , -0.8658, -1.4467, -9.8102])

### Метод Жордана-Гаусса 

### Метод Гаусса с выбором главного элемента 

In [ ]:
def selective_gauss_elimination(A):
    pass

In [13]:
M = array([
    [0.46, 1.72, 2.53, 2.44],
    [1.53, -2.32, -1.83, 2.83],
    [0.75, 0.86, 3.72, 1.06]
])

### Метод LU-разложения 

In [ ]:
def LU_decomposition(A):
    pass

def LU_solution(A, b):
    L, U = LU_decomposition(A)
    y = solve_triangular(L, b)
    x = solve_triangular(U, y)
    return x

In [3]:
A = array([
    [0.18, 2.11, 0.13],
    [0.33, -0.22, -1.0],
    [-1.0, 0.11, 2.0]
])

b = array([0.22, 0.21, 1])

dot(inv(A), b)

array([-4.78963255,  0.63174262, -1.92956212])

In [16]:
A_u = np.triu(A)

In [17]:
%time inv(A_u)

Wall time: 2 ms


array([[  5.65384109e+00,  -4.78908306e+00,  -1.85124089e+00, ...,
          1.05769429e+18,   4.94506710e+16,   2.63534382e+18],
       [  0.00000000e+00,   1.08587507e+00,  -1.52882997e+00, ...,
          6.48022148e+16,   3.02971565e+15,   1.61460755e+17],
       [  0.00000000e+00,   0.00000000e+00,   1.65273361e+00, ...,
         -1.99178656e+17,  -9.31225420e+15,  -4.96272176e+17],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.29839247e+00,  -1.75929030e+00,   1.96188596e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   2.06116542e+00,  -2.71576479e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   2.00762100e+00]])

In [43]:
14.667 - 11.722 * 1.632 + 0.722 * 0.93

-3.791843999999999

In [37]:
A.sum(axis=1) + b

array([ 2.64, -0.68,  2.11])

In [35]:
2 + 0.722 - 11.832 * 0.303

-0.8630960000000001

In [33]:
scipy.linalg.lu(A)

(array([[ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 1.,  0.,  0.]]), array([[ 1.        ,  0.        ,  0.        ],
        [-0.18      ,  1.        ,  0.        ],
        [-0.33      , -0.08625223,  1.        ]]), array([[-1.        ,  0.11      ,  2.        ],
        [ 0.        ,  2.1298    ,  0.49      ],
        [ 0.        ,  0.        , -0.29773641]]))

### Метод Холецкого 

In [75]:
A = array([
    [3.77, 0.56, 1.45],
    [0.56, 9.56, 5.23],
    [1.45, 5.23, 12.87]
])

b = np.array([1.28, 0.87, -2.87])

dot(inv(A), b)

array([ 0.44678991,  0.27564738, -0.38535207])

In [83]:
(3.635 - 0.288 * 1.277 - 0.747 * 0.614) / 1.942

1.4462234809474768

In [65]:
A.sum(axis=1) + b

array([  7.06,  16.22,  16.68])

In [74]:
3.108 - 1.198

1.9100000000000001

In [73]:
1 / 3.108 * (16.68 - 0.747 * 3.635 - 1.629 * 4.93)

1.909165057915058

In [71]:
3.078 + 1.629 + 0.221

4.928

In [67]:
7.06 / 1.942

3.635427394438723

In [57]:
np.sqrt(3.77)

1.9416487838947598

In [63]:
np.sqrt(12.87 - 0.747**2 - 1.629**2)

3.1077886028492991

In [62]:
1 / 3.078 * (5.23 - 0.288 * 0.747)

1.6292605588044187

In [59]:
1.45 / 1.942

0.7466529351184346

### Метод прогонки

In [44]:
A = array([
    [15, 8, 0, 0, 0],
    [2, -15, 4, 0, 0],
    [0, 4, 11, 5, 0],
    [0, 0, -3, 16, -7],
    [0, 0, 0, 3, 8]
])

f = array([92, -84, -77, 15, -11])

In [56]:
(-11 + 3 * 0.594) / (8 + 3 * 0.406)

-1.0

In [45]:
dot(inv(A), f)

array([ 4.,  4., -8., -1., -1.])